### ISSUE TITLE
Instable UI callback on adding new items

### ISSUE THREAD

**Issue by ghost** [CheapTracker/CheapTracker#18]
Sometimes when adding new items, the UI won't get the information that the item was added and will display the progress dialog forever.

**Comment by bLandais** [comment]
Si tu as un scénario qui permet de reproduire le bug, ca peut être pas mal qu'on l'"incorpore" dans les tests UI automatisés

**Comment by bLandais** [comment]
@ChewyBomber Do you still have this problem ?

**Comment by ChewyBomber** [comment]
Fixed in 4d7bafe
