### ISSUE TITLE
Amazon condition exigency ignored

### ISSUE THREAD

**Issue by ChewyBomber** [CheapTracker/CheapTracker#39]
The chosen condition exigency seems to be ignored by the application, e.g. it seems like we get the price for a new item even if we select "USED_ONLY".

**Comment by bLandais** [comment]
The following code is where the condition exigency is used to get the price :

```
        if (conditionFilter == AmazonItemConditionFilter.NEW_ONLY) {
            itemURL += "ref=olp_f_new?f_new=true";
        } else if (conditionFilter == AmazonItemConditionFilter.USED_ONLY) {
            itemURL += "ref=olp_f_used?f_used=true&f_usedAcceptable=true&f_usedGood=true&f_usedLikeNew=true&f_usedVeryGood=true";
        }
```

The "bug" here is more on Amazon's side since we correctly retrieving the information from Amazon...

@ChewyBomber Close this issue... or not ? 😄

**Comment by ChewyBomber** [comment]
Yep
